LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := sqlite3_static

LOCAL_MODULE_FILENAME :=sqlite3_static


LOCAL_CFLAGS += -DSQLITE_HAS_CODEC  

LOCAL_SRC_FILES := shell.c sqlite3.c


LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)

LOCAL_C_INCLUDES := $(LOCAL_PATH)

include $(BUILD_EXECUTABLE)
