#define TK_END_OF_FILE                     1
#define TK_ILLEGAL                         2
#define TK_SPACE                           3
#define TK_UNCLOSED_STRING                 4
#define TK_COMMENT                         5
#define TK_FUNCTION                        6
#define TK_COLUMN                          7
#define TK_AGG_FUNCTION                    8
#define TK_BLOCK                           9
#define TK_VAR                            10
#define TK_ASSIGN                         11
#define TK_SQL                            12
#define TK_SEMI                           13
#define TK_EXPLAIN                        14
#define TK_BEGIN                          15
#define TK_TRANSACTION                    16
#define TK_COMMIT                         17
#define TK_END                            18
#define TK_ROLLBACK                       19
#define TK_CREATE                         20
#define TK_TABLE                          21
#define TK_TEMP                           22
#define TK_LP                             23
#define TK_RP                             24
#define TK_AS                             25
#define TK_COMMA                          26
#define TK_ID                             27
#define TK_ABORT                          28
#define TK_AFTER                          29
#define TK_ASC                            30
#define TK_ATTACH                         31
#define TK_BEFORE                         32
#define TK_CASCADE                        33
#define TK_CLUSTER                        34
#define TK_CONFLICT                       35
#define TK_COPY                           36
#define TK_DATABASE                       37
#define TK_DEFERRED                       38
#define TK_DELIMITERS                     39
#define TK_DESC                           40
#define TK_DETACH                         41
#define TK_EACH                           42
#define TK_FAIL                           43
#define TK_FOR                            44
#define TK_GLOB                           45
#define TK_IGNORE                         46
#define TK_IMMEDIATE                      47
#define TK_INITIALLY                      48
#define TK_INSTEAD                        49
#define TK_LIKE                           50
#define TK_MATCH                          51
#define TK_KEY                            52
#define TK_OF                             53
#define TK_OFFSET                         54
#define TK_PRAGMA                         55
#define TK_RAISE                          56
#define TK_REPLACE                        57
#define TK_RESTRICT                       58
#define TK_ROW                            59
#define TK_STATEMENT                      60
#define TK_TRIGGER                        61
#define TK_VACUUM                         62
#define TK_VIEW                           63
#define TK_OR                             64
#define TK_AND                            65
#define TK_NOT                            66
#define TK_EQ                             67
#define TK_NE                             68
#define TK_ISNULL                         69
#define TK_NOTNULL                        70
#define TK_IS                             71
#define TK_BETWEEN                        72
#define TK_IN                             73
#define TK_GT                             74
#define TK_GE                             75
#define TK_LT                             76
#define TK_LE                             77
#define TK_BITAND                         78
#define TK_BITOR                          79
#define TK_LSHIFT                         80
#define TK_RSHIFT                         81
#define TK_PLUS                           82
#define TK_MINUS                          83
#define TK_STAR                           84
#define TK_SLASH                          85
#define TK_REM                            86
#define TK_CONCAT                         87
#define TK_UMINUS                         88
#define TK_UPLUS                          89
#define TK_BITNOT                         90
#define TK_STRING                         91
#define TK_JOIN_KW                        92
#define TK_INTEGER                        93
#define TK_CONSTRAINT                     94
#define TK_DEFAULT                        95
#define TK_FLOAT                          96
#define TK_NULL                           97
#define TK_PRIMARY                        98
#define TK_UNIQUE                         99
#define TK_CHECK                          100
#define TK_REFERENCES                     101
#define TK_COLLATE                        102
#define TK_ON                             103
#define TK_DELETE                         104
#define TK_UPDATE                         105
#define TK_INSERT                         106
#define TK_SET                            107
#define TK_DEFERRABLE                     108
#define TK_FOREIGN                        109
#define TK_DROP                           110
#define TK_UNION                          111
#define TK_ALL                            112
#define TK_INTERSECT                      113
#define TK_EXCEPT                         114
#define TK_SELECT                         115
#define TK_DISTINCT                       116
#define TK_DOT                            117
#define TK_FROM                           118
#define TK_JOIN                           119
#define TK_USING                          120
#define TK_ORDER                          121
#define TK_BY                             122
#define TK_GROUP                          123
#define TK_HAVING                         124
#define TK_LIMIT                          125
#define TK_WHERE                          126
#define TK_INTO                           127
#define TK_VALUES                         128
#define TK_VARIABLE                       129
#define TK_CASE                           130
#define TK_WHEN                           131
#define TK_THEN                           132
#define TK_ELSE                           133
#define TK_INDEX                          134
#define TK_DECLARE                        135
#define TK_COLON                          136
#define TK_EXCEPTION                      137
#define TK_OTHERS                         138
#define TK_ELSIF                          139
#define TK_IF                             140
#define TK_LOOP                           141
#define TK_WHILE                          142
#define TK_DOTDOT                         143
#define TK_PRINT                          144
#define TK_EXIT                           145
#define TK_RETURN                         146
#define TK_PROCEDURE                      147
#define TK_CALL                           148
#define TK_EXEC                           149
